### ISSUE TITLE
StEWI error

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/ElectricityLCI#102]
Error upon build 
Getting reported emissions for generators...
Traceback (most recent call last):
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\electricitylci\main.py", line 122, in <module>
    main()
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\electricitylci\main.py", line 31, in main
    upstream_df=upstream_df, upstream_dict=upstream_dict
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\electricitylci\__init__.py", line 51, in get_generation_process_df
    generation_process_df=get_gen_plus_netl()
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\electricitylci\__init__.py", line 395, in get_gen_plus_netl
    gen_df = gen.create_generation_process_df()
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\electricitylci\generation.py", line 448, in create_generation_process_df
    from electricitylci.egrid_filter import (
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\electricitylci\egrid_filter.py", line 10, in <module>
    from electricitylci.egrid_emissions_and_waste_by_facility import emissions_and_wastes_by_facility
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\electricitylci\egrid_emissions_and_waste_by_facility.py", line 2, in <module>
    import stewicombo
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\stewicombo\__init__.py", line 5, in <module>
    from stewicombo.overlaphandler import aggregate_and_remove_overlap
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\stewicombo\overlaphandler.py", line 2, in <module>
    from stewicombo.globals import *
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\stewicombo\globals.py", line 3, in <module>
    import chemicalmatcher
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\chemicalmatcher\__init__.py", line 7, in <module>
    from chemicalmatcher.programsynonymlookupbyCAS import programsynonymlookupbyCAS
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\chemicalmatcher\programsynonymlookupbyCAS.py", line 6, in <module>
    from chemicalmatcher.globals import base, config
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\chemicalmatcher\globals.py", line 20, in <module>
    base  = config()['databases']['SRS']['url']
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\chemicalmatcher\globals.py", line 16, in config
    with open(modulepath + 'config.yaml', mode='r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/wesle/AppData/Local/Programs/Python/Python37/lib/site-packages/chemicalmatcher/config.yaml'

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt I get this same error..created this issue for it.

**Comment by WesIngwersen** [comment]
This was resolved and rest of run of main after pip install works and writes out the final file. @jump2conclusionsmatt
